[alembic]
script_location=alembic
prepend_sys_path = .
version_path_separator=os

sqlalchemy.url=postgresql://postgres:Pavu%402631@localhost/fastapi

[post_write_hooks]

[logging]
default_level = INFO
