import json
from rich.console import Console
from rich.panel import Panel
from rich.text import Text
from rich.tree import Tree
from repolens.models import HealthReport

def print_report_json(report: HealthReport):
    print(json.dumps(report.to_dict(), indent=2, default=str))

def _fmt_val(val, default="-"):
    return str(val) if val is not None else default

def print_report_rich(report: HealthReport, days: int):
    console = Console()
    
    repo = report.repository
    act = report.activity
    prs = report.pull_requests
    iss = report.issues
    docs = report.documentation
    
    # Header
    console.print(Panel(
        Text("RepoLens — Repository Health Report", style="bold cyan", justify="center"),
        expand=False
    ))
    
    # Repository
    console.print("\n[bold]Repository[/bold]")
    console.print(f"  {repo.owner}/{repo.name}")
    if repo.primary_language:
        console.print(f"  {repo.primary_language}")
    
    # Overview
    console.print("\n[bold]Overview[/bold]")
    console.print(f"  * Stars       {repo.stars}")
    console.print(f"  Forks          {repo.forks}")
    console.print(f"  Open Issues    {repo.open_issues}")
    console.print(f"  Open PRs       {prs.open_prs}")
    
    # Activity
    console.print(f"\n[bold]Activity — Last {days} Days[/bold]")
    console.print(f"  Commits        {act.commits}")
    console.print(f"  PRs Opened     {act.prs_opened}")
    console.print(f"  PRs Merged     {act.prs_merged}")
    console.print(f"  Issues Opened  {act.issues_opened}")
    console.print(f"  Issues Closed  {act.issues_closed}")
    
    # Pull Requests
    console.print("\n[bold]Pull Requests[/bold]")
    avg_age = f"{prs.average_open_age_days:.1f} days" if prs.average_open_age_days is not None else "-"
    oldest_age = f"{prs.oldest_open_pr_age_days:.1f} days" if prs.oldest_open_pr_age_days is not None else "-"
    console.print(f"  Average Open Age     {avg_age}")
    console.print(f"  Oldest Open PR       {oldest_age}")
    
    # Issues
    console.print("\n[bold]Issues[/bold]")
    old_iss_age = f"{iss.oldest_open_issue_age_days:.1f} days" if iss.oldest_open_issue_age_days is not None else "-"
    console.print(f"  Oldest Open Issue    {old_iss_age}")
    
    # Contributors
    console.print("\n[bold]Contributors[/bold]")
    if report.contributors:
        console.print("  Top contributors")
        for c in report.contributors:
            console.print(f"    {c.login.ljust(15)} {c.contributions}")
    else:
        console.print("  No recent contributors found or fetched.")
    
    # Documentation
    console.print("\n[bold]Repository Hygiene[/bold]")
    console.print(f"  {'[v]' if docs.has_readme else '[x]'} README")
    console.print(f"  {'[v]' if docs.has_license else '[x]'} LICENSE")
    console.print(f"  {'[v]' if docs.has_contributing else '[x]'} CONTRIBUTING")
    console.print(f"  {'[v]' if docs.has_code_of_conduct else '[x]'} CODE_OF_CONDUCT")
    console.print(f"  {'[v]' if docs.has_security else '[x]'} SECURITY")
    
    # Score
    color = "green" if report.health_score >= 80 else ("yellow" if report.health_score >= 50 else "red")
    console.print("\n[bold]Health Score[/bold]")
    console.print(f"  [{color}]{report.health_score} / 100[/{color}]")
    
    # Strengths
    if report.strengths:
        console.print("\n[bold green]Strengths[/bold green]")
        for s in report.strengths:
            console.print(f"  - {s}")
            
    # Reviews
    if report.things_to_review:
        console.print("\n[bold yellow]Things to Review[/bold yellow]")
        for r in report.things_to_review:
            console.print(f"  - {r}")
            
    console.print("\n[dim]Generated by RepoLens[/dim]")
